version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://98.84.196.99:3001
    restart: always
    volumes:
      - .:/app
      - /app/node_modules  # Evitar sobreescribir node_modules
